# Generated by Django 3.2.18 on 2023-05-22 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='customers',
            field=models.ManyToManyField(null=True, related_name='subscriped_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
