# Generated by Django 4.2.1 on 2023-05-25 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_subscript_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscript_products',
            field=models.ManyToManyField(related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
